name: hundred_dot_ui_design
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - lib/assets/icons/phone.svg
    - lib/assets/icons/money.svg
    - lib/assets/icons/transfer.svg
    - lib/assets/icons/ligntning_boult.svg
    - lib/assets/icons/full_screen.svg
    - lib/assets/icons/heart.svg
    - lib/assets/icons/home.svg
    - lib/assets/icons/info.svg
    - lib/assets/icons/credit_card.svg
    - lib/assets/icons/location_pin.svg
    - lib/assets/icons/notification_unread.svg
    - lib/assets/icons/signin.svg
    - lib/assets/icons/plus.svg
    - lib/assets/icons/filter.svg
  fonts:
    - family: HelveticaNeue
      fonts:
        - asset: lib/assets/fonts/HelveticaNeue/HelveticaNeueBold.otf
          weight: 600
        - asset: lib/assets/fonts/HelveticaNeue/HelveticaNeueBoldItalic.otf
          style: italic
          weight: 600
        - asset: lib/assets/fonts/HelveticaNeue/HelveticaNeueMedium.otf
          weight: 500
        - asset: lib/assets/fonts/HelveticaNeue/HelveticaNeueMediumItalic.otf
          style: italic
          weight: 500
        - asset: lib/assets/fonts/HelveticaNeue/HelveticaNeueRoman.otf
          weight: 400
        - asset: lib/assets/fonts/HelveticaNeue/HelveticaNeueItalic.ttf
          weight: 400
          style: italic
        - asset: lib/assets/fonts/HelveticaNeue/HelveticaNeueLight.otf
          weight: 300
        - asset: lib/assets/fonts/HelveticaNeue/HelveticaNeueLightItalic.otf
          style: italic
          weight: 300
        - asset: lib/assets/fonts/HelveticaNeue/HelveticaNeueThin.otf
          weight: 200
        - asset: lib/assets/fonts/HelveticaNeue/HelveticaNeueThinItalic.otf
          style: italic
          weight: 200
        - asset: lib/assets/fonts/HelveticaNeue/HelveticaNeueUltraLight.otf
          weight: 100
        - asset: lib/assets/fonts/HelveticaNeue/HelveticaNeueUltraLightItalic.otf
          style: italic
          weight: 100
  uses-material-design: true
